Repository be14-2nd-spring-is-coming/be14-2nd-springiscomming-marktory, pull requests merged in 2025-03, with the labels that each got.

#7 fix: 일부 스키마 수정 및 더미 데이터 수정
  src/main/resources/sql/authority/authority_schema.sql
  src/main/resources/sql/category/category_schema.sql
  src/main/resources/sql/comment/README.md
  src/main/resources/sql/comment/comment_data.sql
  src/main/resources/sql/hashtag/hashtag_schema.sql
  src/main/resources/sql/likes/likes_schema.sql
  src/main/resources/sql/marktory_data.sql
  src/main/resources/sql/marktory_schema.sql
  src/main/resources/sql/member/README.md
  src/main/resources/sql/member/member_data.sql
  src/main/resources/sql/member/member_schema.sql
  src/main/resources/sql/member_profile_image/member_profile_image_schema.sql
  src/main/resources/sql/member_roles/member_roles_schema.sql
  src/main/resources/sql/member_template/README.md
  src/main/resources/sql/member_template/member_template_data.sql
  src/main/resources/sql/member_template/member_template_schema.sql
  src/main/resources/sql/notice/README.md
  src/main/resources/sql/notice/notice_schema.sql
  src/main/resources/sql/post/README.md
  src/main/resources/sql/post/post_data.sql
  src/main/resources/sql/post/post_schema.sql
  src/main/resources/sql/post_hashtag/post_hashtag_schema.sql
  src/main/resources/sql/public_template/README.md
  src/main/resources/sql/public_template/public_template_data.sql
  src/main/resources/sql/public_template/public_template_schema.sql
  src/main/resources/sql/report/README.md
  src/main/resources/sql/report/report_data.sql
  src/main/resources/sql/report/report_schema.sql
  src/main/resources/sql/report_type/report_type_data.sql
  src/main/resources/sql/report_type/report_type_schema.sql
  src/main/resources/sql/subscribe/subscribe_schema.sql
  src/main/resources/sql/template_space/template_space_schema.sql
Labels: 🔨 Fix

#13 [FEAT] 회원 템플릿 조회및 soft delete
  src/main/resources/sql/marktory_data.sql
  src/main/resources/sql/member_template/README.md
  src/main/resources/sql/member_template/member_template_delete.sql
  src/main/resources/sql/member_template/member_template_insert.sql
  src/main/resources/sql/member_template/member_template_private_select.sql
  src/main/resources/sql/member_template/member_template_public_all_select.sql
  src/main/resources/sql/member_template/member_template_public_select.sql
  src/main/resources/sql/member_template/member_template_subonly_select.sql
  src/main/resources/sql/member_template/member_template_visibility_update.sql
Labels: ✨ Feat

#16 [FIX] : ID 속성 스키마 타입 수정
  build.gradle
  src/main/resources/sql/marktory_data.sql
  src/main/resources/sql/post/post_category_select.sql
Labels: ⚙ Chore, 🔨 Fix

#18 [FEAT] 템플릿 저장 sql
  src/main/resources/sql/member_template/member_template_private_select.sql
Labels: ✨ Feat, 🔨 Fix

#19 [CHORE] template의 content 속서을 LONGTEXT로 변경
  src/main/resources/sql/marktory_data.sql
Labels: ⚙ Chore

#17 [FEAT] : 댓글 쿼리 작성
  src/main/resources/sql/comment/comment_delete.sql
  src/main/resources/sql/comment/comment_insert.sql
  src/main/resources/sql/comment/comment_reply_delete.sql
  src/main/resources/sql/comment/comment_reply_insert.sql
  src/main/resources/sql/comment/comment_reply_select.sql
  src/main/resources/sql/comment/comment_reply_update.sql
  src/main/resources/sql/comment/comment_schema.sql
  src/main/resources/sql/comment/comment_select.sql
  src/main/resources/sql/comment/comment_update.sql
Labels: ✨ Feat

#20 chore : 깃허브 PR 템플릿 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📃 Docs

#22 [FEAT] 구독 위주 sql문 작성
  src/main/resources/sql/member/member_update.sql
  src/main/resources/sql/notice/notice_insert.sql
  src/main/resources/sql/notice/notice_select.sql
  src/main/resources/sql/subscribe/subscribe_delete.sql
  src/main/resources/sql/subscribe/subscribe_insert.sql
  src/main/resources/sql/subscribe/subscribe_notification_update.sql
  src/main/resources/sql/subscribe/subscribe_subscribed_select.sql
  src/main/resources/sql/subscribe/subscribe_subscriber_select.sql
Labels: ✨ Feat

#21 [FEAT] 댓글 목록 조회 기능 구현
  src/main/java/com/sic/marktory/comment/query/controller/CommentController.java
  src/main/java/com/sic/marktory/comment/query/dto/CommentDTO.java
  src/main/java/com/sic/marktory/comment/query/mapper/CommentMapper.java
  src/main/java/com/sic/marktory/comment/query/service/CommentService.java
  src/main/resources/com/sic/marktory/comment/query/mapper/CommentMapper.xml
Labels: ✨ Feat

#24 [FEAT] 게시글 기능 관련 sql
  src/main/resources/sql/likes/likes_delete.sql
  src/main/resources/sql/likes/likes_insert.sql
  src/main/resources/sql/likes/likes_select.sql
  src/main/resources/sql/post/all_post_likes_select.sql
  src/main/resources/sql/post/post_category_select.sql
  src/main/resources/sql/post/post_hashtag_select.sql
  src/main/resources/sql/post/post_insert.sql
  src/main/resources/sql/post/post_likes_select.sql
  src/main/resources/sql/post/post_public_recent_select.sql
  src/main/resources/sql/post/post_soft_delete.sql
  src/main/resources/sql/post/post_subonly_recent_select.sql
  src/main/resources/sql/post/post_update.sql
  src/main/resources/sql/post/post_visibility.sql
Labels: ✨ Feat

#28 [FEAT] 회원 공개 템플릿 전체 조회
  .gitignore
  src/main/java/com/sic/marktory/member_template/query/controller/MemberTemplateController.java
  src/main/java/com/sic/marktory/member_template/query/dto/MemberTemplateDTO.java
  src/main/java/com/sic/marktory/member_template/query/entity/MemberTemplate.java
  src/main/java/com/sic/marktory/member_template/query/mapper/MemberTemplateMapper.java
  src/main/java/com/sic/marktory/member_template/query/service/MemberTemplateService.java
  src/main/java/com/sic/marktory/member_template/query/service/MemberTemplateServiceImpl.java
  src/main/resources/com/sic/marktory/member_template/query/mapper/MemberTemplateMapper.xml
  src/test/java/com/sic/marktory/member_template/query/mapper/MemberTemplateMapperTest.java
Labels: ✨ Feat

#27 [FEAT] 구독, 구독자 목록 조회 기능 구현
  src/main/java/com/sic/marktory/subscribe/command/application/controller/SubscribeController.java
  src/main/java/com/sic/marktory/subscribe/query/controller/SubscribeController.java
  src/main/java/com/sic/marktory/subscribe/query/dto/MemberDTO.java
  src/main/java/com/sic/marktory/subscribe/query/mapper/SubscribeMapper.java
  src/main/java/com/sic/marktory/subscribe/query/service/SubscribeService.java
  src/main/java/com/sic/marktory/subscribe/query/service/SubscribeServiceImpl.java
  src/main/resources/com/sic/marktory/subscribe/query/mapper/SubscribeMapper.xml
Labels: ✨ Feat

#32 [FEAT] 회원가입 진행 완료
  build.gradle
  src/main/java/com/sic/marktory/member/command/application/controller/MemberController.java
  src/main/java/com/sic/marktory/member/command/application/dto/EmailTokenDTO.java
  src/main/java/com/sic/marktory/member/command/application/dto/EmailTokenVerifyDTO.java
  src/main/java/com/sic/marktory/member/command/application/dto/MemberDTO.java
  src/main/java/com/sic/marktory/member/command/application/service/MailService.java
  src/main/java/com/sic/marktory/member/command/application/service/MailServiceImpl.java
  src/main/java/com/sic/marktory/member/command/application/service/MemberService.java
  src/main/java/com/sic/marktory/member/command/application/service/MemberServiceImpl.java
  src/main/java/com/sic/marktory/member/command/domain/aggregate/entity/EmailTokenEntity.java
  src/main/java/com/sic/marktory/member/command/domain/aggregate/entity/MemberEntity.java
  src/main/java/com/sic/marktory/member/command/domain/aggregate/vo/RequestEmailVO.java
  src/main/java/com/sic/marktory/member/command/domain/aggregate/vo/RequestSignupVO.java
  src/main/java/com/sic/marktory/member/command/domain/aggregate/vo/RequestVerifyTokenVO.java
  src/main/java/com/sic/marktory/member/command/domain/aggregate/vo/ResponseEmailVO.java
  src/main/java/com/sic/marktory/member/command/domain/aggregate/vo/ResponseSignupVO.java
  src/main/java/com/sic/marktory/member/command/domain/aggregate/vo/ResponseVerifyTokenVO.java
  src/main/java/com/sic/marktory/member/command/domain/repository/EmailRepository.java
  src/main/java/com/sic/marktory/member/command/domain/repository/MemberRepository.java
  src/main/java/com/sic/marktory/member/common/MailTemplate.java
  src/main/java/com/sic/marktory/member/common/exception/NickNameException.java
  src/main/java/com/sic/marktory/member/common/exception/TokenAlreadyVerifiedException.java
  src/main/java/com/sic/marktory/member/common/exception/TokenExpiredException.java
  src/main/java/com/sic/marktory/member/common/exception/TokenNotFoundException.java
  src/main/java/com/sic/marktory/member/config/AppConfig.java
  src/main/java/com/sic/marktory/member/config/MybatisConfig.java
  src/main/java/com/sic/marktory/member/query/controller/MemberController.java
  src/main/java/com/sic/marktory/member/query/mapper/mapper1.java
  src/main/java/com/sic/marktory/member/query/service/MemberService.java
  src/main/resources/.DS_Store
  src/main/resources/application.yml
  src/main/resources/sql/marktory_data.sql
  src/main/resources/sql/member/member_login.sql
  src/main/resources/sql/member/member_signup.sql
Labels: ✨ Feat

#35 [TEST] 템플릿 작성 command 초안
  src/main/java/com/sic/marktory/common/DateTimeUtil.java
  src/main/java/com/sic/marktory/member_template/command/application/controller/MemberTemplateController.java
  src/main/java/com/sic/marktory/member_template/command/application/dto/MemberTemplateCreateRequest.java
  src/main/java/com/sic/marktory/member_template/command/application/dto/MemberTemplateDTO.java
  src/main/java/com/sic/marktory/member_template/command/application/dto/MemberTemplateDeleteRequest.java
  src/main/java/com/sic/marktory/member_template/command/application/dto/MemberTemplateUpdateRequest.java
  src/main/java/com/sic/marktory/member_template/command/application/service/MemberTemplateService.java
  src/main/java/com/sic/marktory/member_template/command/application/service/MemberTemplateServiceImpl.java
  src/main/java/com/sic/marktory/member_template/command/application/vo/Visibility.java
  src/main/java/com/sic/marktory/member_template/command/domain/aggregate/MemberTemplateEntity.java
  src/main/java/com/sic/marktory/member_template/command/domain/repository/MemberTemplateRepository.java
  src/main/java/com/sic/marktory/member_template/query/controller/MemberTemplateController.java
  src/main/java/com/sic/marktory/member_template/query/entity/MemberTemplate.java
  src/main/java/com/sic/marktory/member_template/query/mapper/MemberTemplateMapper.java
  src/main/java/com/sic/marktory/member_template/query/service/MemberTemplateService.java
  src/main/java/com/sic/marktory/member_template/query/service/MemberTemplateServiceImpl.java
  src/main/resources/com/sic/marktory/member_template/query/mapper/MemberTemplateMapper.xml
  src/main/resources/sql/member_template/member_template_select.sql
Labels: ✨ Feat, ✅ Test, 🔧Refactor

#47 [FEAT] 댓글 추가 기능 구현
  src/main/java/com/sic/marktory/comment/command/application/controller/CommentController.java
  src/main/java/com/sic/marktory/comment/command/application/dto/CommentCreateRequest.java
  src/main/java/com/sic/marktory/comment/command/application/dto/CommentResponseDTO.java
  src/main/java/com/sic/marktory/comment/command/application/dto/CommentUpdateRequest.java
  src/main/java/com/sic/marktory/comment/command/application/service/CommentService.java
  src/main/java/com/sic/marktory/comment/command/application/service/CommentServiceImpl.java
  src/main/java/com/sic/marktory/comment/command/domain/aggregate/CommentEntity.java
  src/main/java/com/sic/marktory/comment/command/domain/repository/CommentRepository.java
  src/main/java/com/sic/marktory/comment/config/AppConfig.java
  src/main/java/com/sic/marktory/comment/query/controller/CommentController.java
  src/main/java/com/sic/marktory/comment/query/service/CommentService.java
Labels: ✨ Feat

#63 [FEAT] 구독 command 구현
  src/main/java/com/sic/marktory/subscribe/command/application/controller/SubscribeController.java
  src/main/java/com/sic/marktory/subscribe/command/application/service/SubscribeService.java
  src/main/java/com/sic/marktory/subscribe/command/application/service/SubscribeServiceImpl.java
  src/main/java/com/sic/marktory/subscribe/command/domain/repository/SubscribeRepository.java
  src/main/java/com/sic/marktory/subscribe/query/mapper/SubscribeMapper.java
Labels: ✨ Feat, 🔧Refactor

#54 [FIX] Configuration 네이밍 수정
  src/main/java/com/sic/marktory/comment/config/AppConfig.java
Labels: 🔨 Fix

#53 [DOC] 스웨거 의존성추가 및 HTML 변환 메소드 구현
  build.gradle
  src/main/java/com/sic/marktory/common/MarkdownUtil.java
Labels: 📃 Docs, ✨ Feat

#60 [FEAT] 구독 기능 구현
  src/main/java/com/sic/marktory/member/command/domain/aggregate/entity/MemberEntity.java
  src/main/java/com/sic/marktory/member/command/domain/repository/MemberRepository.java
  src/main/java/com/sic/marktory/subscribe/command/application/controller/SubscribeController.java
  src/main/java/com/sic/marktory/subscribe/command/application/service/SubscribeService.java
  src/main/java/com/sic/marktory/subscribe/command/application/service/SubscribeServiceImpl.java
  src/main/java/com/sic/marktory/subscribe/command/domain/aggregate/entity/SubscribeEntity.java
  src/main/java/com/sic/marktory/subscribe/command/domain/aggregate/vo/SubscribeRequestVO.java
  src/main/java/com/sic/marktory/subscribe/command/domain/aggregate/vo/SubscribeResponseVO.java
  src/main/java/com/sic/marktory/subscribe/command/domain/repository/SubscribeRepository.java
  src/main/java/com/sic/marktory/subscribe/common/exception/AlreadysubscribeException.java
  src/main/java/com/sic/marktory/subscribe/common/exception/SubscribeException.java
  src/main/java/com/sic/marktory/subscribe/query/controller/SubscribeController.java
  src/main/java/com/sic/marktory/subscribe/query/mapper/SubscribeMapper.java
  src/main/java/com/sic/marktory/subscribe/query/service/SubscribeServiceImpl.java
Labels: ✨ Feat, 🔧Refactor

#64 [FEAT] 로그인 기능 구현 완료
  build.gradle
  src/main/java/com/sic/marktory/config/AppConfig.java
  src/main/java/com/sic/marktory/config/HMACKKeyGenerator.java
  src/main/java/com/sic/marktory/config/MybatisConfig.java
  src/main/java/com/sic/marktory/member/command/application/service/MailServiceImpl.java
  src/main/java/com/sic/marktory/member/command/application/service/MemberServiceImpl.java
  src/main/java/com/sic/marktory/member/command/domain/aggregate/entity/EmailTokenEntity.java
  src/main/java/com/sic/marktory/member/command/domain/aggregate/entity/MemberRolesEntity.java
  src/main/java/com/sic/marktory/member/command/domain/aggregate/vo/RequestLoginVO.java
  src/main/java/com/sic/marktory/member/command/domain/repository/MemberRolesRepository.java
  src/main/java/com/sic/marktory/member/common/security/AuthenticationFilter.java
  src/main/java/com/sic/marktory/member/common/security/JwtAuthenticationProvider.java
  src/main/java/com/sic/marktory/member/common/security/JwtFilter.java
  src/main/java/com/sic/marktory/member/common/security/JwtUtil.java
  src/main/java/com/sic/marktory/member/common/security/WebSecurity.java
  src/main/java/com/sic/marktory/member/config/AppConfig.java
  src/main/java/com/sic/marktory/member/config/MybatisConfig.java
  src/main/java/com/sic/marktory/member/query/controller/MemberController.java
  src/main/java/com/sic/marktory/member/query/dto/AuthorityDTO.java
  src/main/java/com/sic/marktory/member/query/dto/MemberByEmailDTO.java
  src/main/java/com/sic/marktory/member/query/dto/MemberDTO.java
  src/main/java/com/sic/marktory/member/query/dto/MemberWithRoleDTO.java
  src/main/java/com/sic/marktory/member/query/mapper/AuthorityMapper.java
  src/main/java/com/sic/marktory/member/query/mapper/MemberMapper.java
  src/main/java/com/sic/marktory/member/query/mapper/MemberRolesMapper.java
  src/main/java/com/sic/marktory/member/query/mapper/mapper1.java
  src/main/java/com/sic/marktory/member/query/service/MemberService.java
  src/main/java/com/sic/marktory/member/query/service/MemberServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/com/sic/marktory/member/query/mapper/MemberMapper.xml
  src/main/resources/sql/marktory_data.sql
Labels: ✨ Feat

#66 [FEAT] 회원 비밀번호 더미 데이터 변경
  src/main/java/com/sic/marktory/config/AppConfig.java
  src/main/java/com/sic/marktory/member/common/security/JwtAuthenticationProvider.java
  src/main/resources/com/sic/marktory/member/query/mapper/MemberMapper.xml
  src/main/resources/sql/marktory_data.sql
  src/main/resources/sql/member/member_data.sql
Labels: ✨ Feat, 🔧Refactor

#62 [FEAT] 댓글 예외 처리 구현
  src/main/java/com/sic/marktory/comment/command/application/controller/CommentController.java
  src/main/java/com/sic/marktory/comment/command/application/dto/CommentResponseDTO.java
  src/main/java/com/sic/marktory/comment/command/application/service/CommentServiceImpl.java
  src/main/java/com/sic/marktory/comment/common/exception/CommentAlreadyDeletedException.java
  src/main/java/com/sic/marktory/comment/common/exception/CommentNotFoundException.java
  src/main/java/com/sic/marktory/comment/common/exception/EmptyCommentContentException.java
  src/main/java/com/sic/marktory/comment/common/exception/UnauthorizedCommentAccessException.java
Labels: ✨ Feat

#71 [FEAT] : 마크다운으로 작성된 회원 템플릿을 HTML로 반환
  src/main/java/com/sic/marktory/member_template/command/application/controller/MemberTemplateController.java
  src/main/java/com/sic/marktory/member_template/command/application/service/MemberTemplateService.java
  src/main/java/com/sic/marktory/member_template/command/application/service/MemberTemplateServiceImpl.java
  src/main/java/com/sic/marktory/member_template/command/domain/aggregate/MemberTemplateEntity.java
Labels: ✨ Feat

#69 [REACTOR] 시간 적용 방식 변경
  src/main/java/com/sic/marktory/comment/command/application/dto/CommentResponseDTO.java
  src/main/java/com/sic/marktory/comment/command/application/service/CommentServiceImpl.java
  src/main/java/com/sic/marktory/comment/command/domain/aggregate/CommentEntity.java
Labels: 🔧Refactor

#72 [FEAT] 더미 데이터 수정
  src/main/resources/sql/marktory_data.sql
Labels: ⚙ Chore

#74 [TEST] 댓글 테스트 코드 작성
  src/test/java/com/sic/marktory/comment/command/application/service/CommentServiceTest.java
  src/test/java/com/sic/marktory/comment/query/mapper/CommentMapperTest.java
Labels: ✅ Test

#75 [FEAT] 마이페이지 Query 기능 구현
  src/main/java/com/sic/marktory/member/command/application/service/MemberService.java
  src/main/java/com/sic/marktory/member/query/controller/MemberController.java
  src/main/java/com/sic/marktory/member/query/dto/MemberAndCommentDTO.java
  src/main/java/com/sic/marktory/member/query/dto/MemberAndPostDTO.java
  src/main/java/com/sic/marktory/member/query/dto/MemberAndTemplateDTO.java
  src/main/java/com/sic/marktory/member/query/dto/MemberPageDTO.java
  src/main/java/com/sic/marktory/member/query/mapper/MemberMapper.java
  src/main/java/com/sic/marktory/member/query/service/MemberService.java
  src/main/java/com/sic/marktory/member/query/service/MemberServiceImpl.java
  src/main/resources/com/sic/marktory/member/query/mapper/MemberMapper.xml
  src/main/resources/sql/member/member_mypage.sql
Labels: ✨ Feat

#78 [FEAT] 구독 알림 변경 기능 구현
  src/main/java/com/sic/marktory/subscribe/command/application/controller/SubscribeController.java
  src/main/java/com/sic/marktory/subscribe/command/application/service/SubscribeService.java
  src/main/java/com/sic/marktory/subscribe/command/application/service/SubscribeServiceImpl.java
  src/main/java/com/sic/marktory/subscribe/command/domain/aggregate/entity/SubscribeEntity.java
Labels: ✨ Feat

#80 [DOCS] Update README.md
  README.md
Labels: 📃 Docs

#82 [DOCS] Update README.md
  README.md
Labels: 📃 Docs

#83 [DOCS] Update README.md
  README.md
Labels: 📃 Docs

#84 [DOCS] Update README.md
  README.md
Labels: 📃 Docs

#85 [DOCS] Update README.md
  README.md
Labels: 📃 Docs

#86 [DOCS] Update README.md
  README.md
Labels: 📃 Docs

#88 [Docs] 리드미 오타 수정
  README.md
Labels: 📃 Docs
